### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by miquellaboria** [MetalPetal/SurfaceBlur#1]
When I execute, I get an error:

> Error Domain=MTLLibraryErrorDomain Code=5 "Function mtiSurfaceBlur was not found in the library" UserInfo={NSLocalizedDescription=Function mtiSurfaceBlur was not found in the library}

My code is:
`
        guard let cgImage = image.cgImage else { return }

        let filter = MTISurfaceBlurFilter(radius: radius)
        filter.threshold = threshold
        filter.inputImage = MTIImage(__cgImage: cgImage, options: nil, isOpaque: true)

        let options = MTIContextOptions()

        guard let device = MTLCreateSystemDefaultDevice(), let context = try? MTIContext(device: device, options: options), let outputImage = filter.outputImage else {
            return
        }

        do {
            let filteredImage = try context.makeCGImage(from: outputImage)

            filteredImg = UIImage(cgImage: filteredImage)
            importImage.image = filteredImg
        } catch {
            print(error)
        }`

Any help is appreciated! Thanks!

**Comment by YuAo** [comment]
Try change the function name here to "metalpetal::surfaceblur::mtiSurfaceBlur"
https://github.com/MetalPetal/SurfaceBlur/blob/22d87260a9ca5ae4cf5454ed27f3375639db84da/SurfaceBlur/MTISurfaceBlurFilter.m#L40

**Comment by YuAo** [comment]
Fixed via 744f8cb
